### ISSUE TITLE
Is there a guide on how to use this?

### ISSUE THREAD

**Issue by SkySkrimp** [Geordan9/FRFCTCryptTool#1]
Whenever I use it I get a file that has no extension and when I write it in the file does not work. I am trying to use it on Fearless revolution Borderlands 3 cheat engine table.
![image](https://user-images.githubusercontent.com/99281210/153045052-46c2c3cf-d7c0-4cfe-9017-de2b11142789.png)

**Comment by Geordan9** [comment]
The file with no extension is the encrypted table. You most likely attempted to decrypt the proxy table used to redirect you to the app along with the file/table ID for the app to download in memory. As of right now, the old url format works, but the encryption is different. They also added some cloudflare stuff to the download link on their forum posts so my code can't retrieve the original file name.

**Comment by bad1dea** [comment]
https://github.com/FlareSolverr/FlareSolverr

**Comment by Geordan9** [comment]
Ah, thank you. This is useful. However, since I have another "tool" that utilizes the app itself and still works, I'll probably leave it as that unless something changes in the future. "Tool" I'm referring to:
https://opencheattables.org/viewtopic.php?f=12&t=269
